language: python
jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.8
#    - os: windows
#      python: 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libhdf5-serial-dev
install:
  - pip install -U pip
  - pip install --progress-bar off h5py
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off nose

script:
  - pip install .
  - nosetests tests
  - detect-blobs --help
  - collect-patches --help
 